builds:
  - env:
    - CGO_ENABLED=1
    binary: gpu-cloudwatch-reporting
    goos:
      - linux
    goarch:
      - amd64
archives:
  -
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
release:
  github:
    owner: ohsawa0515
    name: gpu-cloudwatch-reporting